version: '3'
services:
  # Postgres
  postgres:
    image: postgres
    container_name: fastfeet_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastfeet
    ports:
      - '5432:5432'
  # Redis
  redis:
    image: 'redis:alpine'
    container_name: fastfeet_redis
    ports:
      - '6379:6379'
      server:
        build: .
        container_name: fastfeet_server
        entrypoint: sh /usr/app/scripts/init.sh
        ports:
          - '3333:3333'
        volumes:
          - ./:/usr/app/
        env_file:
          - .env
        depends_on:
          - postgres
          - redis
  # Queue process
  queue:
    build: ./
    container_name: fastfeet_queue
    command: yarn queue
    volumes:
      - ./:/usr/app/
    env_file:
      - ./.env
